Optional Squid proxy on port 3128 to access from remote scanner
Secure-Compliance-Solutions-LLC/GVM-Docker pull request #345
Opened 2022-07-15 11:56 UTC by vendito-david

Certain restricted environments have no internet connectivity and updating the image is problematic in those environments with rsync.

The OpenVAS image could use the existing SSH tunnel (forward a local port next to the unix socket) to access a Squid proxy running on the main GVM instance. Starting the proxy would be optional and in case it is not started, it wouldn't be possible to access it from the OpenVAS.

## Summary

Adding optional squid proxy which starts when SQUID=true env variable is set. Can be used from remote scanner if the port is forwarded in the existing tunnel.

### Checklist

- [ x ] [Update Documentation](https://github.com/Secure-Compliance-Solutions-LLC/gitbook) extra variables added for documentation.

### Fixed Bug/Issues solved:

Created issues: #16 in OpenVAS-Docker and #344 in GVM-Docker.
https://github.com/Secure-Compliance-Solutions-LLC/OpenVAS-Docker/issues/16
https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker/issues/344

2022-07-15 11:57 UTC, vendito-david commented
Relevant pull in OpenVAS-Docker:
https://github.com/Secure-Compliance-Solutions-LLC/OpenVAS-Docker/pull/17

2022-08-01 12:45 UTC, Dexus requested changes

2022-08-01 12:45 UTC, Dexus commented on Dockerfile
> +    SQUID=${SSHD:-false} \
```suggestion
    SQUID=${SQUID:-false} \
```

2023-08-18 15:06 UTC, closed without merging

2023-08-18 15:06 UTC, korzorro commented
The project is deprecated and no longer accepting pull requests.